### ISSUE TITLE
Gerar painel para consulta ao de_para das fontes de recurso

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/matriz-fonte-stn-dadosmg#24]
O GRP vai entrar em 2024 com suporte para as alterações provenientes da Portaria 710.

Um painel (contendo a possibilidade de download de um arquivo excel) com o de_para vai ser útil para os técnicos da DCMEFO (demanda do Pedro) e potencialmente útil para técnicos orçamentários no estado inteiro.

Precisamos inserir informações descritivas nas bases desse repositório e possivelmente fazer o mapeamento em relação a classificação atual e a fonte completa do GRP (Grupo da Fonte, Fonte, Detalhamento da Fonte).

**Comment by hslinhares** [comment]
@fjuniorr painel criado d61b9c8fe7fe4f5cfe1a6cbdebedd9a12318c737
